<?php
class TestController extends BaseController {
    /**
     * Setup the base for creating template responses
     */
    public function __construct() {
        // Pass in the base for all the views
        parent::__construct();

        // Tell what is the base for all login
        $this->view_base = 'test/';
    }

    /**
     * List Accounts
     *
     *
     * @return TemplateResponse
     */
    protected function index() {
        $categories = array(
            'CANDAR Fabric Nailhead Trim Armchair' => 'Dining Room > Arm Chairs'
            , 'ADLER Fabric Armchair' => 'Dining Room > Arm Chairs'
            , 'LINZER Bicast Leather King-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'LINZER Bicast Leather Queen-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'CAVILLINO  Bi-cast Leather Full-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'CAVILLINO Leather Queen Bed' => 'Bedroom > Beds > Complete Beds'
            , 'CAVILLINO Bi-cast Leather Queen-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'TEO Bi-cast Leather Full-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'TEO Bi-cast Leather Queen-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'MARINA Bi-cast Leather Queen-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX Faux Leather Full-size Bed, Dark Brown' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX Faux Leather Full-size Bed, White' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX Faux Leather Queen-size Bed, Dark Brown' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX Faux Leather Queen-size Bed, White' => 'Bedroom > Beds > Complete Beds'
            , 'CAPRIVA Sleigh King-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'CAPRIVA Sleigh Queen-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'CAPRIVA Sleigh California King-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX Dark Brown Bi-cast Leather King-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'COLFAX White Bi-cast Leather King-size Bed' => 'Bedroom > Beds > Complete Beds'
            , 'WEST PARK 4PC Cal-King Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'WEST PARK 5PC Cal-King Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'WEST PARK 4PC King Bedroom Set ' => 'Bedroom > Bedroom Groups'
            , 'WEST PARK 5PC King Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'WEST PARK 4PC Queen Bedroom Set ' => 'Bedroom > Bedroom Groups'
            , 'WEST PARK 5PC Queen Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 4-piece Sleigh California King-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 4-piece Sleigh King-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 4-piece Sleigh Queen-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 5-piece Sleigh California King-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 5-piece Sleigh King-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'CAPRIVA 5-piece Sleigh Queen-size Bedroom Set' => 'Bedroom > Bedroom Groups'
            , 'SOUTHPORT Bonded Leather Lounger' => 'Leather > Leather Chairs'
            , 'ELIZABETH FABRIC CHAISE LOUNGER' => 'Leather > Leather Chaise'
            , 'CAPRIVA 6-drawer Chest' => 'Bedroom > Chests'
            , 'ELONA Dining Buffet' => 'Dining Room > Buffets'
            , 'ELONA Dining Table' => 'Dining Room > Tables'
            , 'WEST PARK Hardwood Dresser' => 'Bedroom > Dressers'
            , 'CAPRIVA 9-drawer Dresser and Mirror Set' => 'Bedroom > Dresser & Mirror'
            , 'LANO Black Top Grain Leather Electric Recliner' => 'Leather > Leather Recliners'
            , 'JERICHO Leather Arm Chair (Set of 2)' => 'Dining Room > Arm Chairs'
            , 'AVENUE SIX Top Grain Leather Chair and Ottoman' => 'Leather > Leather Chair w/ Ottoman'
            , 'AVENUE SIX White Top Grain Leather Chair and Ottoman' => 'Leather > Leather Chair w/ Ottoman'
            , 'JERICHO Leather Side Chair (Set of 2)' => 'Dining Room > Side Chairs'
            , 'CAPRIVA 2 Drawer Nightstand' => 'Bedroom > Night Stands'
            , 'BROMLEY Fabric Ottoman' => 'Living Room > Ottomans'
            , 'FOURA Italian Leather Ottoman' => 'Leather > Leather Ottomans'
            , 'PARKER Top Grain Leather Ottoman' => 'Leather > Leather Ottomans'
            , 'ZARA 5 Piece Eco Teak Wood Outdoor Dining Set' => 'Dining Room > Dining Room Groups'
            , 'TANADARI Ridgeium Stainless Steel Outdoor Dining Set' => 'Dining Room > Dining Room Groups'
            , 'MERU Deepseater Outdoor Living Room Set' => 'Dining Room > Dining Room Groups'
            , 'DINAH-LEE Dark Brown Bonded Leather Recliner' => 'Leather > Leather Recliners'
            , ' VEDA Hand Rubbed Top Grain Leather Pushback Recliner' => 'Leather > Leather Recliners'
            , 'ARON Hand Rubbed Pushback Leather Recliner' => 'Leather > Leather Recliners'
            , 'Amden Hand Rubbed Top Grain Leather Pushback Recliner' => 'Leather > Leather Recliners'
            , 'Roca Leather Pushback Recliner' => 'Leather > Leather Recliners'
            , 'TEKANA Premium Italian Leather Sectional Sofa' => 'Leather > Leather Sectionals'
            , 'PECTURM 5 Piece Top Grain Leather Modular Sectional' => 'Leather > Leather Living Room Groups'
            , 'BROMLEY Fabric Sectional' => 'Living Room > Living Room Groups'
            , 'BEVERLY Brown Sectional Sofa' => 'Living Room > Sectionals'
            , 'TUSCANOVA Premium Top Grain Leather Sectional Sofa' => 'Leather > Leather Sectionals'
            , 'VANA Premium Hand Rubbed Leather Sectional Sofa' => 'Living Room > Living Room Groups'
            , 'Sienna Premium Top Grain Leather Sectional Sofa' => 'Leather > Leather Sectionals'
            , 'CADAH Mocha Microsuede Sectional Sofa with Ottoman' => 'Living Room > Living Room Groups'
            , 'DERLENA Microsuede Sectional Sofa and Storage Ottoman Set' => 'Living Room > Living Room Groups'
            , 'CHANNA Sectional Sofa and Ottoman' => 'Living Room > Living Room Groups'
            , 'HEPER Brown Leather Sofa and Loveseat Set' => 'Leather > Leather Living Room Groups'
            , 'PARKS Premium Top Grain Leather Sofa, Loveseat, and Armchair Set ' => 'Leather > Leather Living Room Groups'
            , 'CANDAR Fabric Nailhead Trim Sofa and Loveseat' => 'Living Room > Living Room Package'
            , 'ARJENA Two Tone Brown Leather Sofa' => 'Leather > Leather Living Room Groups'
            , 'ASPER & LYNN Premium Top Grain Reclining Leather Sofa and 2 Armchairs' => 'Leather > Leather Living Room Groups'
            , 'GAILMARIE Premium Top Grain Leather Sofa, Loveseat, and Armchair Set' => 'Leather > Leather Living Room Groups'
            , 'HOUST Premium Semi-Aniline Leather Sofa, Loveseat, and Armchair Set ' => 'Leather > Leather Living Room Groups'
            , 'HANO Premium Top Grain Leather Sofa, Loveseat, and Armchair Set ' => 'Leather > Leather Living Room Groups'
            , 'Marx Top Grain Leather Sofa, Loveseat, and Armchair Set' => 'Leather > Leather Living Room Groups'
            , 'CASSIE 72 Inch Solid Oak Wood TV Console' => 'Home Entertainment > Consoles'
            , 'AUSSIE 64 Inch Solid Oak Wood TV Console' => 'Home Entertainment > Consoles'
            , 'DEAGEN TV Console' => 'Home Entertainment > Entertainment Centers'
            , 'HARPER-LEE  TV Console' => 'Home Entertainment > Entertainment Centers'
            , 'NAOMI TV Console' => 'Home Entertainment > Entertainment Centers'
            , 'name' => 'category'
            , 'London Top Grain Leather Armchair' => 'Leather > Leather Chairs'
            , 'LALIA Italian Leather Armchair' => 'Leather > Leather Chairs'
            , 'LEA-LEE Italian Leather Armchair' => 'Leather > Leather Chairs'
            , 'BRENTEENA Top Grain Leather Armchair' => 'Leather > Leather Chairs'
            , 'Arcadian Premium Italian Leather Armchair' => 'Leather > Leather Chairs'
            , 'VISTA SEA Premium Italian Leather Oversized Chair' => 'Leather > Leather Chairs'
            , 'BERNEEN Italian Leather Armchair' => 'Leather > Leather Chairs'
            , 'LEDGER Top Grain Leather Sofa and Armchair' => 'Leather > Leather Living Room Groups'
            , 'London Top Grain Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'LALIA Italian Leather 3PC Sofa, Armchair & Ottoman' => 'Leather > Leather Living Room Groups'
            , 'LALIA Italian Leather 2PC Sofa and  Armchair Set' => 'Leather > Leather Living Room Groups'
            , 'LEA-LEE Italian Leather 2PC Sofa and Armchair' => 'Leather > Leather Living Room Groups'
            , 'LEA-LEE Italian Leather 2PC Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'LEVARI Reclining Leather Sofa and Chair' => 'Leather > Leather Living Room Groups'
            , 'LEVARI Reclining Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'HOGAN Reclining Italian Leather Sofa and Chair' => 'Leather > Leather Living Room Groups'
            , 'HOGAN Reclining Italian Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'HERZINA Leather Pushback Reclining Sofa and Chair' => 'Leather > Leather Living Room Groups'
            , 'HERZINA Leather Pushback Reclining Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'CHESTEN 3PC Set - Sofa, Loveseat and Armchair ' => 'Leather > Leather Living Room Groups'
            , 'BRENTEENA Top Grain Leather Sofa and Chair' => 'Leather > Leather Living Room Groups'
            , 'BRENTEENA Top Grain Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'Eileen Top Grain Leather Sofa, Loveseat, and Armchair Set' => 'Leather > Leather Living Room Groups'
            , 'Foyer Premium Italian Leather Sofa and Armchair Set' => 'Leather > Leather Living Room Groups'
            , 'VISTA SEA Premium Italian Leather Oversized Sofa and Chair' => 'Leather > Leather Living Room Groups'
            , 'VISTA SEA Premium Italian Leather Oversized Sofa, Chair, and Ottoman' => 'Leather > Leather Living Room Groups'
            , 'PEARLA 2 Piece Set, Premium Italian Leather Armchair and Ottoman' => 'Leather > Leather Living Room Groups'
            , 'PEARLA 3 Piece Set, Premium Italian Leather Sofa, Armchair, and Ottoman' => 'Leather > Leather Living Room Groups'
            , 'PEARLA 3 Piece Set, Premium Italian Leather Sofa, Loveseat, and Armchair' => 'Leather > Leather Living Room Groups'
            , 'MACINA 2 Piece Set, Premium Italian Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'ADLER Fabric Sofa and Loveseat Set' => 'Leather > Leather Living Room Groups'
            , 'BERNEEN Italian Leather Sofa and Armchair' => 'Leather > Leather Living Room Groups'
            , 'BERNEEN Italian Leather Sofa and Loveseat' => 'Leather > Leather Living Room Groups'
            , 'TERNA NELY Bonded Leather Storage Ottoman Bench' => 'Leather > Leather Ottomans'
            , 'BARNABE Bonded Leather Double Cushion Storage Ottoman' => 'Leather > Leather Ottomans'
            , 'LEVARI Reclining Leather Armchair' => 'Leather > Leather Recliners'
            , 'HOGAN Reclining Italian Leather Armchair' => 'Leather > Leather Recliners'
            , 'HERZINA Leather Pushback Reclining Armchair' => 'Leather > Leather Recliners'
            , 'Noma 3 Piece Premium Top Grain Leather Reclining Set' => 'Leather > Leather Reclining Furniture > Leather Reclining Group'
            , 'RILEY 3 Piece Premium Top Grain Leather Reclining Set' => 'Leather > Leather Reclining Furniture > Leather Reclining Group'
            , 'Lexia Premium Top Grain Sectional and Round Ottoman Set' => 'Leather > Leather Sectionals'
            , 'MACALEA Fabric Sectional' => 'Leather > Leather Sectionals'
            , 'ERFILA Italian Leather Sectional' => 'Leather > Leather Sectionals'
            , 'MICHAELA Bonded Leather Sectional Sofa' => 'Leather > Leather Sectionals'
            , 'Foyer Premium Italian Leather Sofa' => 'Leather > Leather Sofas'
            , 'AUSSIE Microsuede Rocker Recliner, Beige' => 'Living Room > Recliners'
            , 'AUSSIE Microsuede Rocker Recliner, Brown' => 'Living Room > Recliners'
            , 'MALIBU Microsuede Pushback Recliner' => 'Living Room > Recliners'
            , 'KARA Microsuede Rocker Recliner' => 'Living Room > Recliners'
            , 'VENAH Microsuede Pushback Recliner' => 'Living Room > Recliners'
            , 'SNAPPER Beige Microsuede Pushback Recliner' => 'Living Room > Recliners'
            , 'SNAPPER Dark Brown Microsuede Pushback Recliner' => 'Living Room > Recliners'
            , 'Beachwood Micro-suede Pushback Recliner' => 'Living Room > Recliners'
            , 'HAMDEN Dark Brown Microsuede Sectional' => 'Living Room > Sectionals'
            , 'PASADINI Sectional Sofa' => 'Living Room > Sectionals'
            , 'ARIZONA Italian Leather Sectional Sofa' => 'Living Room > Sectionals'

        );

        $skus = array( 'Noma 3 Piece Premium Top Grain Leather Reclining Set'
        , 'London Top Grain Leather Armchair'
        , 'LEDGER Top Grain Leather Sofa and Armchair'
        , 'London Top Grain Leather Sofa and Loveseat'
        , 'LALIA Italian Leather Armchair'
        , 'LALIA Italian Leather 3PC Sofa, Armchair & Ottoman'
        , 'LALIA Italian Leather 2PC Sofa and  Armchair Set'
        , 'LEA-LEE Italian Leather Armchair'
        , 'LEA-LEE Italian Leather 2PC Sofa and Armchair'
        , 'LEA-LEE Italian Leather 2PC Sofa and Loveseat'
        , 'LEVARI Reclining Leather Armchair'
        , 'LEVARI Reclining Leather Sofa and Chair'
        , 'LEVARI Reclining Leather Sofa and Loveseat'
        , 'HOGAN Reclining Italian Leather Armchair'
        , 'HOGAN Reclining Italian Leather Sofa and Chair'
        , 'HOGAN Reclining Italian Leather Sofa and Loveseat'
        , 'HERZINA Leather Pushback Reclining Armchair'
        , 'HERZINA Leather Pushback Reclining Sofa and Chair'
        , 'HERZINA Leather Pushback Reclining Sofa and Loveseat'
        , 'RILEY 3 Piece Premium Top Grain Leather Reclining Set'
        , 'HAMDEN Dark Brown Microsuede Sectional'
        , 'CADAH Mocha Microsuede Sectional Sofa with Ottoman'
        , 'CHESTEN 3PC Set - Sofa, Loveseat and Armchair '
        , 'BRENTEENA Top Grain Leather Armchair'
        , 'BRENTEENA Top Grain Leather Sofa and Chair'
        , 'BRENTEENA Top Grain Leather Sofa and Loveseat'
        , 'Lexia Premium Top Grain Sectional and Round Ottoman Set'
        , 'Eileen Top Grain Leather Sofa, Loveseat, and Armchair Set'
        , 'Sienna Premium Top Grain Leather Sectional Sofa'
        , 'Arcadian Premium Italian Leather Armchair'
        , 'Foyer Premium Italian Leather Sofa'
        , 'Foyer Premium Italian Leather Sofa and Armchair Set'
        , 'DERLENA Microsuede Sectional Sofa and Storage Ottoman Set'
        , 'PASADINI Sectional Sofa'
        , 'MACALEA Fabric Sectional'
        , 'TERNA NELY Bonded Leather Storage Ottoman Bench'
        , 'BARNABE Bonded Leather Double Cushion Storage Ottoman'
        , 'CHANNA Sectional Sofa and Ottoman'
        , 'CHANNA Sectional Sofa and Ottoman'
        , 'BROMLEY Fabric Sectional'
        , 'BROMLEY Fabric Ottoman'
        , 'VISTA SEA Premium Italian Leather Oversized Chair'
        , 'VISTA SEA Premium Italian Leather Oversized Sofa and Chair'
        , 'VISTA SEA Premium Italian Leather Oversized Sofa, Chair, and Ottoman'
        , 'ERFILA Italian Leather Sectional'
        , 'PEARLA 2 Piece Set, Premium Italian Leather Armchair and Ottoman'
        , 'PEARLA 3 Piece Set, Premium Italian Leather Sofa, Armchair, and Ottoman'
        , 'PEARLA 3 Piece Set, Premium Italian Leather Sofa, Loveseat, and Armchair'
        , 'MACINA 2 Piece Set, Premium Italian Leather Sofa and Loveseat'
        , 'ELIZABETH FABRIC CHAISE LOUNGER'
        , 'CANDAR Fabric Nailhead Trim Armchair'
        , 'CANDAR Fabric Nailhead Trim Sofa and Loveseat'
        , 'ADLER Fabric Armchair'
        , 'ADLER Fabric Sofa and Loveseat Set'
        , 'MICHAELA Bonded Leather Sectional Sofa'
        , 'BERNEEN Italian Leather Armchair'
        , 'BERNEEN Italian Leather Sofa and Armchair'
        , 'BERNEEN Italian Leather Sofa and Loveseat'
        , 'ARIZONA Italian Leather Sectional Sofa'
        , 'FOURA Italian Leather Ottoman'
        , 'TEKANA Premium Italian Leather Sectional Sofa'
        , 'DINAH-LEE Dark Brown Bonded Leather Recliner'
        , 'AUSSIE Microsuede Rocker Recliner, Beige'
        , 'AUSSIE Microsuede Rocker Recliner, Brown'
        , 'MALIBU Microsuede Pushback Recliner'
        , 'KARA Microsuede Rocker Recliner'
        , 'VENAH Microsuede Pushback Recliner'
        , 'SNAPPER Beige Microsuede Pushback Recliner'
        , 'SNAPPER Dark Brown Microsuede Pushback Recliner'
        , 'Beachwood Micro-suede Pushback Recliner'
        , 'Roca Leather Pushback Recliner'
        , ' VEDA Hand Rubbed Top Grain Leather Pushback Recliner'
        , 'Amden Hand Rubbed Top Grain Leather Pushback Recliner'
        , 'WEST PARK Hardwood Dresser'
        , 'WEST PARK 4PC Cal-King Bedroom Set'
        , 'WEST PARK 5PC Cal-King Bedroom Set'
        , 'WEST PARK 4PC King Bedroom Set '
        , 'WEST PARK 5PC King Bedroom Set'
        , 'WEST PARK 4PC Queen Bedroom Set '
        , 'WEST PARK 5PC Queen Bedroom Set'
        , 'CAPRIVA Sleigh King-size Bed'
        , 'CAPRIVA Sleigh Queen-size Bed'
        , 'CAPRIVA Sleigh California King-size Bed'
        , 'CAPRIVA 2 Drawer Nightstand'
        , 'CAPRIVA 6-drawer Chest'
        , 'CAPRIVA 9-drawer Dresser and Mirror Set'
        , 'CAPRIVA 4-piece Sleigh California King-size Bedroom Set'
        , 'CAPRIVA 4-piece Sleigh King-size Bedroom Set'
        , 'CAPRIVA 4-piece Sleigh Queen-size Bedroom Set'
        , 'CAPRIVA 5-piece Sleigh California King-size Bedroom Set'
        , 'CAPRIVA 5-piece Sleigh King-size Bedroom Set'
        , 'CAPRIVA 5-piece Sleigh Queen-size Bedroom Set'
        , 'DEAGEN TV Console'
        , 'HARPER-LEE  TV Console'
        , 'NAOMI TV Console'
        , 'CASSIE 72 Inch Solid Oak Wood TV Console'
        , 'AUSSIE 64 Inch Solid Oak Wood TV Console'
        , 'GAILMARIE Premium Top Grain Leather Sofa, Loveseat, and Armchair Set'
        , 'HEPER Brown Leather Sofa and Loveseat Set'
        , 'LINZER Bicast Leather King-size Bed'
        , 'LINZER Bicast Leather Queen-size Bed'
        , 'SOUTHPORT Bonded Leather Lounger'
        , 'BEVERLY Brown Sectional Sofa'
        , 'CAVILLINO  Bi-cast Leather Full-size Bed'
        , 'CAVILLINO Leather Queen Bed'
        , 'CAVILLINO Bi-cast Leather Queen-size Bed'
        , 'TEO Bi-cast Leather Full-size Bed'
        , 'TEO Bi-cast Leather Queen-size Bed'
        , 'MARINA Bi-cast Leather Queen-size Bed'
        , 'COLFAX Faux Leather Full-size Bed, Dark Brown'
        , 'COLFAX Faux Leather Full-size Bed, White'
        , 'COLFAX Dark Brown Bi-cast Leather King-size Bed'
        , 'COLFAX White Bi-cast Leather King-size Bed'
        , 'COLFAX Faux Leather Queen-size Bed, Dark Brown'
        , 'COLFAX Faux Leather Queen-size Bed, White'
        , 'MERU Deepseater Outdoor Living Room Set'
        , 'ZARA 5 Piece Eco Teak Wood Outdoor Dining Set'
        , 'TANADARI Ridgeium Stainless Steel Outdoor Dining Set'
        , 'PARKER Top Grain Leather Ottoman'
        , 'TUSCANOVA Premium Top Grain Leather Sectional Sofa'
        , 'Marx Top Grain Leather Sofa, Loveseat, and Armchair Set'
        , 'ARJENA Two Tone Brown Leather Sofa'
        , 'PARKS Premium Top Grain Leather Sofa, Loveseat, and Armchair Set '
        , 'VANA Premium Hand Rubbed Leather Sectional Sofa'
        , 'HOUST Premium Semi-Aniline Leather Sofa, Loveseat, and Armchair Set '
        , 'HANO Premium Top Grain Leather Sofa, Loveseat, and Armchair Set '
        , 'ARON Hand Rubbed Pushback Leather Recliner'
        , 'LANO Black Top Grain Leather Electric Recliner'
        , 'AVENUE SIX Top Grain Leather Chair and Ottoman'
        , 'AVENUE SIX White Top Grain Leather Chair and Ottoman'
        , 'PECTURM 5 Piece Top Grain Leather Modular Sectional'
        , 'ASPER & LYNN Premium Top Grain Reclining Leather Sofa and 2 Armchairs'
        , 'JERICHO Leather Side Chair (Set of 2)'
        , 'JERICHO Leather Arm Chair (Set of 2)'
        , 'ELONA Dining Table'
        , 'ELONA Dining Buffet'

        );

        foreach ( $skus as $sku ) {
            echo $categories[$sku] . "<br>\n";
        }

        return new HtmlResponse( 'heh' );
    }

    /**
     * Login
     *
     * @return bool
     */
//    protected function get_logged_in_user() {
//        if ( defined('CLI') && true == CLI ) {
//            $this->user = new User();
//            return true;
//        }
//
//        return false;
//    }
}