<?php
class TestController extends BaseController {
    /**
     * Setup the base for creating template responses
     */
    public function __construct() {
        // Pass in the base for all the views
        parent::__construct();

        // Tell what is the base for all login
        $this->view_base = 'test/';
    }

    /**
     * List Accounts
     *
     *
     * @return TemplateResponse
     */
    protected function index() {
        $categories = array(
            'RTA-00397B-GLS' => 'Home Office > Home Office Desks'
            , 'RTA-0039LC-BK' => 'Home Office > Home Office Desks'
            , 'RTA-0040L-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-1458-PN' => 'Home Office > Home Office Desks'
            , 'RTA-1459-WAL' => 'Home Office > Home Office Desks'
            , 'RTA-1460-ES' => 'Home Office > Home Office Desks'
            , 'RTA-1462-PN' => 'Home Office > Home Office Desks'
            , 'RTA-1565-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-1880-BK' => 'Home Office > Home Office Desks'
            , 'RTA-1880-WHT' => 'Home Office > Home Office Desks'
            , 'RTA-220AB-WHT' => 'Home Office > Home Office Desks'
            , 'RTA-2012-CH' => 'Home Office > Home Office Desks'
            , 'RTA-2018-ES18' => 'Home Office > Home Office Desks'
            , 'RTA-2018-GPH06' => 'Home Office > Home Office Desks'
            , 'RTA-2202-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-2202-M615' => 'Home Office > Home Office Desks'
            , 'RTA-2212-M615' => 'Home Office > Home Office Desks'
            , 'RTA-2350B-GPH06' => 'Home Office > Home Office Desks'
            , 'RTA-2706A-WG01' => 'Home Office > Home Office Desks'
            , 'RTA-325-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-3309-BK46' => 'Home Office > Home Office Desks'
            , 'RTA-3325-ES18' => 'Home Office > Home Office Desks'
            , 'RTA-3327-DH33' => 'Home Office > Home Office Desks'
            , 'RTA-3331-M615' => 'Home Office > Home Office Desks'
            , 'RTA-3520-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-3520-M615' => 'Home Office > Home Office Desks'
            , 'RTA-3784-GLS' => 'Home Office > Home Office Desks'
            , 'RTA-3802-GLS' => 'Home Office > Home Office Desks'
            , 'RTA-3803-GPH06' => 'Home Office > Home Office Desks'
            , 'RTA-3806-M615' => 'Home Office > Home Office Desks'
            , 'RTA-4804L-ES' => 'Home Office > Home Office Desks'
            , 'RTA-4805L-CFE' => 'Home Office > Home Office Desks'
            , 'RTA-4985-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-7337-GLS' => 'Home Office > Home Office Desks'
            , 'RTA-8104-CH36' => 'Home Office > Home Office Desks'
            , 'RTA-8211-ES18' => 'Home Office > Home Office Desks'
            , 'RTA-8211-M615' => 'Home Office > Home Office Desks'
            , 'RTA-8336-C09' => 'Home Office > Home Office Desks'
            , 'RTA-8338-DH33' => 'Home Office > Home Office Desks'
            , 'RTA-B001N-ES18' => 'Home Office > Laptop Stand'
            , 'RTA-B001N-GPH06' => 'Home Office > Laptop Stand'
            , 'RTA-B001N-M615' => 'Home Office > Laptop Stand'
            , 'RTA-B002-GPH06' => 'Home Office > Laptop Stand'
            , 'RTA-B002-WG01' => 'Home Office > Laptop Stand'
            , 'RTA-B003-GPH06' => 'Home Office > Laptop Stand'
            , 'RTA-B003-M615' => 'Home Office > Laptop Stand'
            , 'RTA-B005-BK46' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-B005-CH36' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-B006-GPH06' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-B018-GPH06' => 'Home Office > Home Office Desks'
            , 'RTA-M1104-BK' => 'Home Office > Home Office Desks'
            , 'RTA-Q203-PW' => 'Home Office > Home Office Desks'
            , 'RTA-Q207-BW' => 'Home Office > Home Office Desks'
            , 'RTA-Q328-DB/SG' => 'Home Office > Home Office Desks'
            , 'RTA-Q328-PW' => 'Home Office > Home Office Desks'
            , 'RTA-S10-GPH06' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-S11-W-BK46' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-S06-GPH06' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-S08-GPH06' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-S13-W-ASH20' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-S13-W-ES18' => 'Home Office > Home Office File Cabinets and Carts'
            , 'RTA-0034-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-0097M-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-0098M-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-073-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-0930-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-0930-CH' => 'Home Office > Home Office Desk Chair'
            , 'RTA-709M-BRN' => 'Home Office > Home Office Desk Chair'
            , 'RTA-722H-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-722H-BRN' => 'Home Office > Home Office Desk Chair'
            , 'RTA-722V-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-734H-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-802H-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-8050-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-8050-BL' => 'Home Office > Home Office Desk Chair'
            , 'RTA-8060-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-8070-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-80X5-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-80X5-SG' => 'Home Office > Home Office Desk Chair'
            , 'RTA-9105-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-919H-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-919H-CH' => 'Home Office > Home Office Desk Chair'
            , 'RTA-9300B-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-M101-BK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-M101-LM' => 'Home Office > Home Office Desk Chair'
            , 'RTA-M101-ORG' => 'Home Office > Home Office Desk Chair'
            , 'RTA-M101-WHT' => 'Home Office > Home Office Desk Chair'
            , 'RTA-Q030-BL' => 'Home Office > Home Office Desk Chair'
            , 'RTA-Q030-PNK' => 'Home Office > Home Office Desk Chair'
            , 'RTA-7732-GLS' => 'Home Entertainment > TV Stand'
            , 'RTA-7733-BK' => 'Home Entertainment > TV Stand'
            , 'RTA-7734-BK' => 'Home Entertainment > TV Stand'
            , 'RTA-7735-BK' => 'Home Entertainment > TV Stand'
            , 'RTA-8807-W-WN' => 'Home Entertainment > TV Stand'
            , 'RTA-8811-W-HRY' => 'Home Entertainment > TV Stand'
            , 'RTA-8830-W-MPL' => 'Home Entertainment > TV Stand'
            , 'RTA-8895-WAL' => 'Home Entertainment > TV Stand'
            , 'RTA-8895-HRY' => 'Home Entertainment > Media Storage Cabinets'
            , 'RTA-8896-W-BK' => 'Home Entertainment > Media Storage Cabinets'
            , 'RTA-8897-W-BK' => 'Home Entertainment > Media Storage Cabinets'
            , 'RTA-9910-BK' => 'Home Entertainment > TV Stand'
            , 'RTA-9920-BK' => 'Home Entertainment > TV Stand'
        );

        $skus = array( 'CLOUSEOUT ITEMS'
        , 'RTA-SI2718-GPH06'
        , 'RTA-SI2910-BK'
        , 'RTA-SI2911-WHT'
        , 'TECHNI MOBILI DESKS '
        , 'RTA-00397B-GLS'
        , 'RTA-0039LC-BK'
        , 'RTA-0040L-CH36'
        , 'RTA-1305-PN'
        , 'RTA-1458-PN'
        , 'RTA-1459-WAL'
        , 'RTA-1460-ES'
        , 'RTA-1462-PN'
        , 'RTA-1565-CH36'
        , 'RTA-1880-BK'
        , 'RTA-1880-WHT'
        , 'RTA-220AB-WHT'
        , 'RTA-2012-CH'
        , 'RTA-2018-ES18'
        , 'RTA-2018-GPH06'
        , 'RTA-2202-CH36'
        , 'RTA-2202-M615'
        , 'RTA-2212-M615'
        , 'RTA-2350B-GPH06'
        , 'RTA-2706A-WG01'
        , 'RTA-325-CH36'
        , 'RTA-3309-BK46'
        , 'RTA-3325-ES18'
        , 'RTA-3327-DH33'
        , 'RTA-3331-M615'
        , 'RTA-3520-CH36'
        , 'RTA-3520-M615'
        , 'RTA-3784-GLS'
        , 'RTA-3802-GLS'
        , 'RTA-3803-GPH06'
        , 'RTA-3806-M615'
        , 'RTA-4804L-ES'
        , 'RTA-4805L-CFE'
        , 'RTA-4985-CH36'
        , 'RTA-7337-GLS'
        , 'RTA-8104-CH36'
        , 'RTA-8211-ES18'
        , 'RTA-8211-M615'
        , 'RTA-8336-C09'
        , 'RTA-8338-DH33'
        , 'RTA-B001N-ES18'
        , 'RTA-B001N-GPH06'
        , 'RTA-B001N-M615'
        , 'RTA-B002-GPH06'
        , 'RTA-B002-WG01'
        , 'RTA-B003-GPH06'
        , 'RTA-B003-M615'
        , 'RTA-B005-BK46'
        , 'RTA-B005-CH36'
        , 'RTA-B006-GPH06'
        , 'RTA-B018-GPH06'
        , 'RTA-M1104-BK'
        , 'RTA-Q203-PW'
        , 'RTA-Q207-BW'
        , 'RTA-Q328-DB/SG'
        , 'RTA-Q328-PW'
        , 'TECHNI MOBILI ROLLING STORAGE CABINETS'
        , 'RTA-S10-GPH06'
        , 'RTA-S11-W-BK46'
        , 'TECHNI MOBILI FILE CABINETS'
        , 'RTA-S06-GPH06'
        , 'RTA-S08-GPH06'
        , 'RTA-S13-W-ASH20'
        , 'RTA-S13-W-ES18'
        , 'TECHNI MOBILI CHAIRS '
        , 'RTA-0034-BK'
        , 'RTA-0097M-BK'
        , 'RTA-0098M-BK'
        , 'RTA-073-BK'
        , 'RTA-0930-BK'
        , 'RTA-0930-CH'
        , 'RTA-709M-BRN'
        , 'RTA-722H-BK'
        , 'RTA-722H-BRN'
        , 'RTA-722V-BK'
        , 'RTA-734H-BK'
        , 'RTA-802H-BK'
        , 'RTA-8050-BK'
        , 'RTA-8050-BL'
        , 'RTA-8060-BK'
        , 'RTA-8070-BK'
        , 'RTA-80X5-BK'
        , 'RTA-80X5-SG'
        , 'RTA-9105-BK'
        , 'RTA-919H-BK'
        , 'RTA-919H-CH'
        , 'RTA-9300B-BK'
        , 'RTA-M101-BK'
        , 'RTA-M101-LM'
        , 'RTA-M101-ORG'
        , 'RTA-M101-WHT'
        , 'RTA-Q030-BL'
        , 'RTA-Q030-PNK'
        , 'TECHNI MOBILI TV STANDS'
        , 'RTA-7732-GLS'
        , 'RTA-7733-BK'
        , 'RTA-7734-BK'
        , 'RTA-7735-BK'
        , 'RTA-8807-W-WN'
        , 'RTA-8811-W-HRY'
        , 'RTA-8830-W-MPL'
        , 'RTA-8895-WAL'
        , 'RTA-8895-HRY'
        , 'RTA-8896-W-BK'
        , 'RTA-8897-W-BK'
        , 'RTA-9910-BK'
        , 'RTA-9920-BK'

        );

        foreach ( $skus as $sku ) {
            echo $categories[$sku] . "<br>\n";
        }

        return new HtmlResponse( 'heh' );
    }

    /**
     * Login
     *
     * @return bool
     */
//    protected function get_logged_in_user() {
//        if ( defined('CLI') && true == CLI ) {
//            $this->user = new User();
//            return true;
//        }
//
//        return false;
//    }
}