<?php
$data['checklist'] = "INSERT INTO `checklists` ( `website_id`, `type`, `date_created`) VALUES ( [website_id], 'Website Setup', NOW() );";
$data['checklist_items'] = "INSERT INTO `checklist_website_items` ( `checklist_id`, `checklist_item_id` ) VALUES
([checklist_id], 1),
([checklist_id], 2),
([checklist_id], 3),
([checklist_id], 4),
([checklist_id], 5),
([checklist_id], 6),
([checklist_id], 7),
([checklist_id], 8),
([checklist_id], 9),
([checklist_id], 10),
([checklist_id], 11),
([checklist_id], 12),
([checklist_id], 13),
([checklist_id], 14),
([checklist_id], 15),
([checklist_id], 16),
([checklist_id], 17),
([checklist_id], 18),
([checklist_id], 19),
([checklist_id], 20),
([checklist_id], 21),
([checklist_id], 22),
([checklist_id], 23),
([checklist_id], 24),
([checklist_id], 25),
([checklist_id], 26),
([checklist_id], 27),
([checklist_id], 28),
([checklist_id], 29),
([checklist_id], 30),
([checklist_id], 31),
([checklist_id], 32),
([checklist_id], 33),
([checklist_id], 34),
([checklist_id], 35),
([checklist_id], 36),
([checklist_id], 37);";
?>